### ISSUE TITLE
QA: Domain Events

### ISSUE THREAD

**Issue by vuoriv** [nemit/paju-ddd#30]
Domain Events on ollut puhe, mutta asia on jäänyt minulle epäselväksi. Voitaisiin tässä tiketissä purkaa ajatusta auki.

- Miten Domain Events eroaa tämän projektin `StateChangeEvent` eventeistä?
   - Tai miten Domain Events eroaa Event Sourcing eventeistä?
- Mihin tarkoitukseen Domain Events on tarkoitettu?
- Onko mahdollista toteuttaa osaksi tätä?
- Onko Pajulahdessa tarve Domain Eventteihin?

Olen ymmärtänyt että domain event on isompi kokonaisuus tapahtumia, joka on tarve julkaista domain eventtinä.

//cc @kimmoeklund

**Comment by kimmoeklund** [comment]
Link from Joni http://blog.sapiensworks.com/post/2016/06/06/practical-event-sourcing-and-cqrs-benefits

Like in the A+ES pattern, ES events are considered domain events, but I'm still not convinced. Maybe working more on the model will show if state change events and domain events become more of the same.

**Comment by vuoriv** [comment]
Closing this for now
